server:
  port: 5000
  servlet:
    context-path: /conta-aqui-service
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true
spring:
  datasource:
    url: jdbc:postgresql://ep-red-sound-acya6n98-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_O8B1fQZzqUHm
  application:
    name: conta-aqui-service
    admin:
        enabled: false
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
jwt:
  key:
    private: classpath:app.key
    public: classpath:app.pub